apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6IjQ5YTYwY2RiLWJlMGYtNDA3Mi05YWUwLWM0Y2ExMzE5NmIwNiIsImFwcGxpY2F0aW9uX25hbWUiOiJjdXN0b21lcnMiLCJhcHBsaWNhdGlvbl91cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1jdXN0b21lcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sImFwcGxpY2F0aW9uX3ZlcnNpb24iOiIwNzYzMTMwNC0xNzViLTQxYjgtODUwOC1kMmM4NmMwYWQ5NGQiLCJjZl9hcGkiOiJodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8iLCJsaW1pdHMiOnsiZGlzayI6MTAyNCwiZmRzIjoxNjM4NCwibWVtIjoxMDI0fSwibmFtZSI6ImN1c3RvbWVycyIsInNwYWNlX2lkIjoiMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmIiwic3BhY2VfbmFtZSI6ImVudGVycHJpc2UiLCJ1cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1jdXN0b21lcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sInVzZXJzIjpudWxsLCJ2ZXJzaW9uIjoiMDc2MzEzMDQtMTc1Yi00MWI4LTg1MDgtZDJjODZjMGFkOTRkIn0=
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: customers-vcapasenv
type: Opaque
