apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6IjQ0YTQ1OGM0LWRlYTAtNDI1Yi04OWFjLWFiOTVkOWQxMmFmNyIsImFwcGxpY2F0aW9uX25hbWUiOiJnYXRld2F5IiwiYXBwbGljYXRpb25fdXJpcyI6WyJlbnRlcnByaXNlLWFwcC01MjUyMTA4MzktZ2F0ZXdheS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8iXSwiYXBwbGljYXRpb25fdmVyc2lvbiI6IjUzYzJkZmQ0LWEyZDktNDZlZS1iZmE2LWFmYjRjODE1NTcyNCIsImNmX2FwaSI6Imh0dHBzOi8vYXBpLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbyIsImxpbWl0cyI6eyJkaXNrIjoxMDI0LCJmZHMiOjE2Mzg0LCJtZW0iOjEwMjR9LCJuYW1lIjoiZ2F0ZXdheSIsInNwYWNlX2lkIjoiMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmIiwic3BhY2VfbmFtZSI6ImVudGVycHJpc2UiLCJ1cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbyJdLCJ1c2VycyI6bnVsbCwidmVyc2lvbiI6IjUzYzJkZmQ0LWEyZDktNDZlZS1iZmE2LWFmYjRjODE1NTcyNCJ9
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: gateway-vcapasenv
type: Opaque
