apiVersion: v1
data:
  VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6IjE3MmQ2MGU1LWZhNDEtNDU1YS1iN2QzLTBhOTBlN2E4YTQzZCIsImFwcGxpY2F0aW9uX25hbWUiOiJvcmRlcnMiLCJhcHBsaWNhdGlvbl91cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1vcmRlcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sImFwcGxpY2F0aW9uX3ZlcnNpb24iOiI3ODg0YTEyMC0wNDBhLTQ0NGMtYmFmMi1iODhkNTg4OGQ3MjciLCJjZl9hcGkiOiJodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8iLCJsaW1pdHMiOnsiZGlzayI6MTAyNCwiZmRzIjoxNjM4NCwibWVtIjoxMDI0fSwibmFtZSI6Im9yZGVycyIsInNwYWNlX2lkIjoiMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmIiwic3BhY2VfbmFtZSI6ImVudGVycHJpc2UiLCJ1cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1vcmRlcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sInVzZXJzIjpudWxsLCJ2ZXJzaW9uIjoiNzg4NGExMjAtMDQwYS00NDRjLWJhZjItYjg4ZDU4ODhkNzI3In0=
  VCAP_SERVICES: e30=
kind: Secret
metadata:
  creationTimestamp: null
  name: orders-vcapasenv
type: Opaque
