
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi5saW1pdHMuZGlzazogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5mZHM6IDE2Mzg0CnZjYXAuYXBwbGljYXRpb24ubGltaXRzLm1lbTogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLnVzZXJzOiAKdmNhcC5hcHBsaWNhdGlvbi52ZXJzaW9uOiA1M2MyZGZkNC1hMmQ5LTQ2ZWUtYmZhNi1hZmI0YzgxNTU3MjQKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl92ZXJzaW9uOiA1M2MyZGZkNC1hMmQ5LTQ2ZWUtYmZhNi1hZmI0YzgxNTU3MjQKdmNhcC5hcHBsaWNhdGlvbi5jZl9hcGk6IGh0dHBzOi8vYXBpLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3VyaXM6IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3VyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLm5hbWU6IGdhdGV3YXkKdmNhcC5hcHBsaWNhdGlvbi5zcGFjZV9pZDogMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmCnZjYXAuYXBwbGljYXRpb24uc3BhY2VfbmFtZTogZW50ZXJwcmlzZQp2Y2FwLmFwcGxpY2F0aW9uLnVyaXM6IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnVyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX2lkOiA0NGE0NThjNC1kZWEwLTQyNWItODlhYy1hYjk1ZDlkMTJhZjcKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl9uYW1lOiBnYXRld2F5
kind: Secret
metadata:
    creationTimestamp: null
    name: gateway-vcapasspringbootproperties
type: Opaque

...
