
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
    creationTimestamp: null
    name: target-enterprise-app-clone-build-push
spec:
    params:
        - description: registry-domain/namespace where the output image should be pushed.
          name: image-registry-url
          type: string
    tasks:
        - name: clone-1
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: target-enterprise-app-shared-data
        - name: build-push-1
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/customers
            - name: DOCKERFILE
              value: customers/Dockerfile
            - name: CONTEXT
              value: customers
          runAfter:
            - clone-1
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: target-enterprise-app-shared-data
        - name: clone-2
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-1
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: target-enterprise-app-shared-data
        - name: build-push-2
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/frontend
            - name: DOCKERFILE
              value: frontend/Dockerfile
            - name: CONTEXT
              value: frontend
          runAfter:
            - clone-2
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: target-enterprise-app-shared-data
        - name: clone-3
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-2
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: target-enterprise-app-shared-data
        - name: build-push-3
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/orders
            - name: DOCKERFILE
              value: orders/Dockerfile
            - name: CONTEXT
              value: orders
          runAfter:
            - clone-3
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: target-enterprise-app-shared-data
        - name: clone-4
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-3
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: target-enterprise-app-shared-data
        - name: build-push-4
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/inventory
            - name: DOCKERFILE
              value: inventory/Dockerfile
            - name: CONTEXT
              value: inventory
          runAfter:
            - clone-4
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: target-enterprise-app-shared-data
        - name: clone-5
          params:
            - name: url
              value: '<TODO: insert git repo url>'
            - name: revision
              value: main
            - name: deleteExisting
              value: "true"
          runAfter:
            - build-push-4
          taskRef:
            name: git-clone
          workspaces:
            - name: output
              workspace: target-enterprise-app-shared-data
        - name: build-push-5
          params:
            - name: IMAGE
              value: $(params.image-registry-url)/gateway
            - name: DOCKERFILE
              value: gateway/Dockerfile
            - name: CONTEXT
              value: gateway
          runAfter:
            - clone-5
          taskRef:
            name: kaniko
          workspaces:
            - name: source
              workspace: target-enterprise-app-shared-data
    workspaces:
        - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
          name: target-enterprise-app-shared-data

...
