
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl9pZDogODczNTM5M2ItYTFmNy00MjExLWE2YjMtNDU5YTdjNWU2NzQ5CnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fdmVyc2lvbjogMTE2ZjdhODYtNzU0My00ZDliLWEyZTUtY2FkNzllYmEwNmEwCnZjYXAuYXBwbGljYXRpb24uY2ZfYXBpOiBodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi5saW1pdHMuZGlzazogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5mZHM6IDE2Mzg0CnZjYXAuYXBwbGljYXRpb24ubGltaXRzLm1lbTogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLnNwYWNlX25hbWU6IGVudGVycHJpc2UKdmNhcC5hcHBsaWNhdGlvbi51cmlzOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4MzktaW52ZW50b3J5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnVyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1pbnZlbnRvcnkuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24udmVyc2lvbjogMTE2ZjdhODYtNzU0My00ZDliLWEyZTUtY2FkNzllYmEwNmEwCnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fbmFtZTogaW52ZW50b3J5CnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fdXJpczogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LWludmVudG9yeS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl91cmlzWzBdOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4MzktaW52ZW50b3J5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLm5hbWU6IGludmVudG9yeQp2Y2FwLmFwcGxpY2F0aW9uLnNwYWNlX2lkOiAzMDJmZmUwYy0zODNkLTQ0Y2EtODcyYi1hZjc3YmM1OWY2M2YKdmNhcC5hcHBsaWNhdGlvbi51c2Vyczog
kind: Secret
metadata:
    creationTimestamp: null
    name: inventory-vcapasspringbootproperties
type: Opaque

...
