
---
apiVersion: v1
data:
    VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6IjMzM2M2YTNhLTRjZDUtNDYwMy04Y2Y3LTE5YzVkYjliZjc0NSIsImFwcGxpY2F0aW9uX25hbWUiOiJmcm9udGVuZCIsImFwcGxpY2F0aW9uX3VyaXMiOlsiZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LWZyb250ZW5kLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbyJdLCJhcHBsaWNhdGlvbl92ZXJzaW9uIjoiNmFlNmMzNWEtMzAxMi00NWUyLWFkNGMtNzc4MjhiNDZjN2Y0IiwiY2ZfYXBpIjoiaHR0cHM6Ly9hcGkuMjAuMjMxLjEyMS4xODQubmlwLmlvIiwibGltaXRzIjp7ImRpc2siOjEwMjQsImZkcyI6MTYzODQsIm1lbSI6MjA0OH0sIm5hbWUiOiJmcm9udGVuZCIsInNwYWNlX2lkIjoiMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmIiwic3BhY2VfbmFtZSI6ImVudGVycHJpc2UiLCJ1cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1mcm9udGVuZC4yMC4yMzEuMTIxLjE4NC5uaXAuaW8iXSwidXNlcnMiOm51bGwsInZlcnNpb24iOiI2YWU2YzM1YS0zMDEyLTQ1ZTItYWQ0Yy03NzgyOGI0NmM3ZjQifQ==
    VCAP_SERVICES: e30=
kind: Secret
metadata:
    creationTimestamp: null
    name: frontend-vcapasenv
type: Opaque

...
